import type { Skill } from "./types";

export const SKILL_CATEGORIES = [
  "primary",
  "frontend",
  "backend",
  "environment",
  "learning",
  "experiment",
  "archive",
] as const;

export const SKILL_GROUPS = [
  "languages",
  "frameworks",
  "libraries",
  "styling",
  "storage",
  "infrastructure",
  "apps",
  "docs",
  "testing",
  "monitoring",
] as const;

export const SKILLS: Skill[] = [
  {
    id: "typescript",
    name: "TypeScript",
    icon: "i-skill-icons:typescript",
    group: "languages",
    categories: ["primary", "frontend", "backend"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "i-skill-icons:javascript",
    group: "languages",
    categories: ["primary", "frontend", "backend"],
  },
  {
    id: "elysiajs",
    name: "ElysiaJS",
    icon: "i-skill-icons:elysia-light dark:i-skill-icons:elysia-dark",
    group: "frameworks",
    categories: ["primary", "backend"],
  },
  {
    id: "html",
    name: "HTML",
    icon: "i-skill-icons:html",
    group: "languages",
    categories: ["primary", "frontend"],
  },
  {
    id: "css",
    name: "CSS",
    icon: "i-skill-icons:css",
    group: "languages",
    categories: ["primary", "frontend"],
  },
  {
    id: "scss",
    name: "SCSS",
    icon: "i-skill-icons:sass",
    group: "styling",
    categories: ["frontend"],
  },
  {
    id: "less",
    name: "Less",
    icon: "i-skill-icons:less-dark",
    group: "styling",
    categories: ["frontend"],
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    icon: "i-skill-icons:tailwindcss-light dark:i-skill-icons:tailwindcss-dark",
    group: "styling",
    categories: ["primary", "frontend"],
  },
  {
    id: "react",
    name: "React",
    icon: "i-skill-icons:react-light dark:i-skill-icons:react-dark",
    group: "frameworks",
    categories: ["primary", "frontend"],
  },
  {
    id: "solid",
    name: "SolidJS",
    icon: "i-skill-icons:solidjs-light dark:i-skill-icons:solidjs-dark",
    group: "frameworks",
    categories: ["primary", "frontend"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    icon: "i-skill-icons:nextjs-light dark:i-skill-icons:nextjs-dark",
    group: "frameworks",
    categories: ["primary", "frontend"],
  },
  {
    id: "astro",
    name: "Astro",
    icon: "i-skill-icons:astro",
    group: "frameworks",
    categories: ["frontend"],
  },
  {
    id: "unocss",
    name: "UnoCSS",
    icon: "i-logos:unocss",
    group: "styling",
    categories: ["frontend"],
  },
  {
    id: "zod",
    name: "Zod",
    icon: "i-logos:zod",
    group: "libraries",
    categories: ["frontend"],
  },
  {
    id: "vite",
    name: "Vite",
    icon: "i-skill-icons:vite-light dark:i-skill-icons:vite-dark",
    group: "libraries",
    categories: ["frontend"],
  },
  {
    id: "vitest",
    name: "Vitest",
    icon: "i-skill-icons:vitest-light dark:i-skill-icons:vitest-dark",
    group: "testing",
    categories: ["frontend"],
  },
  {
    id: "playwright",
    name: "Playwright",
    icon: "i-logos:playwright",
    group: "testing",
    categories: ["frontend"],
  },
  {
    id: "python",
    name: "Python",
    icon: "i-skill-icons:python-light dark:i-skill-icons:python-dark",
    group: "languages",
    categories: ["primary", "backend"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: "i-skill-icons:fastapi",
    group: "frameworks",
    categories: ["primary", "backend"],
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    icon: "i-skill-icons:postgresql-light dark:i-skill-icons:postgresql-dark",
    group: "storage",
    categories: ["primary", "backend"],
  },
  {
    id: "sqlite",
    name: "SQLite",
    icon: "i-skill-icons:sqlite",
    group: "storage",
    categories: ["backend"],
  },
  {
    id: "redis",
    name: "Redis",
    icon: "i-skill-icons:redis-light dark:i-skill-icons:redis-dark",
    group: "storage",
    categories: ["primary", "backend"],
  },
  {
    id: "git",
    name: "Git",
    icon: "i-skill-icons:git",
    group: "infrastructure",
    categories: ["environment"],
  },
  {
    id: "docker",
    name: "Docker",
    icon: "i-skill-icons:docker",
    group: "infrastructure",
    categories: ["environment"],
  },
  {
    id: "nginx",
    name: "NGINX",
    icon: "i-skill-icons:nginx",
    group: "infrastructure",
    categories: ["environment"],
  },
  {
    id: "nix",
    name: "Nix",
    icon: "i-skill-icons:nix-light dark:i-skill-icons:nix-dark",
    group: "infrastructure",
    categories: ["environment"],
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    icon: "i-skill-icons:vscode-light dark:i-skill-icons:vscode-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "nvim",
    name: "Neovim",
    icon: "i-skill-icons:neovim-light dark:i-skill-icons:neovim-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "webstorm",
    name: "Webstorm",
    icon: "i-skill-icons:webstorm-light dark:i-skill-icons:webstorm-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "obsidian",
    name: "Obsidian",
    icon: "i-skill-icons:obsidian-light dark:i-skill-icons:obsidian-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "figma",
    name: "Figma",
    icon: "i-skill-icons:figma-light dark:i-skill-icons:figma-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    icon: "i-skill-icons:gitlab-light dark:i-skill-icons:gitlab-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "github",
    name: "GitHub",
    icon: "i-skill-icons:github-light dark:i-skill-icons:github-dark",
    group: "apps",
    categories: ["environment"],
  },
  {
    id: "grafana",
    name: "Grafana",
    icon: "i-skill-icons:grafana-light dark:i-skill-icons:grafana-dark",
    group: "monitoring",
    categories: ["environment"],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    icon: "i-skill-icons:prometheus",
    group: "monitoring",
    categories: ["environment"],
  },
  {
    id: "md",
    name: "Markdown",
    icon: "i-skill-icons:markdown-light dark:i-skill-icons:markdown-dark",
    group: "docs",
    categories: ["environment"],
  },
  {
    id: "latex",
    name: "LaTeX",
    icon: "i-skill-icons:latex-light dark:i-skill-icons:latex-dark",
    group: "docs",
    categories: ["environment"],
  },
  {
    id: "angular",
    name: "Angular",
    icon: "i-skill-icons:angular-light dark:i-skill-icons:angular-dark",
    group: "frameworks",
    categories: ["learning"],
  },
  {
    id: "go",
    name: "Go",
    icon: "i-skill-icons:golang",
    group: "languages",
    categories: ["learning"],
  },
  {
    id: "rust",
    name: "Rust",
    icon: "i-skill-icons:rust",
    group: "languages",
    categories: ["experiment"],
  },
  {
    id: "svelte",
    name: "Svelte",
    icon: "i-skill-icons:svelte",
    group: "frameworks",
    categories: ["experiment"],
  },
  {
    id: "qwik",
    name: "Qwik",
    icon: "i-logos:qwik-icon",
    group: "frameworks",
    categories: ["experiment"],
  },
  {
    id: "csharp",
    name: "C#",
    icon: "i-skill-icons:cs",
    group: "languages",
    categories: ["archive", "backend"],
  },
  {
    id: "django",
    name: "Django",
    icon: "i-skill-icons:django",
    group: "frameworks",
    categories: ["archive", "backend"],
  },
];
